
#ウィンドウのサイズ
WINDOWS_WIDTH = 500
WINDOWS_HEIGHT = 500

LEFT_FRAME_WIDTH = 250
LEFT_FRAME_HEIGHT = WINDOWS_HEIGHT / 2

RIGHT_FRAME_WIDTH = 250
RIGHT_FRAME_HEIGHT = WINDOWS_HEIGHT

#ボタンの位置
LOAD_BUTTON_RELX = 0.05
LOAD_BUTTON_RELY = 0.05

EXPORT_BUTTON_RELX = 0.05
EXPORT_BUTTON_RELY = 0.25